apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: wireguard-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: WireguardPeer is the Schema for the wireguardpeers API
      displayName: Wireguard Peer
      kind: WireguardPeer
      name: wireguardpeers.vpn.example.com
      version: v1alpha1
    - description: Wireguard is the Schema for the wireguards API
      displayName: Wireguard
      kind: Wireguard
      name: wireguards.vpn.example.com
      version: v1alpha1
  description: operates
  displayName: wireguard-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - vpn
  links:
  - name: Wireguard Operator
    url: https://wireguard-operator.domain
  maintainers:
  - email: jodevsa@gmail.com
    name: subhi
  maturity: alpha
  provider:
    name: wireguard-operator
  version: 0.0.0
